# Site Settings
baseurl: ""
url : "https://jenniferlukk.github.io"

# Blog Settings
theme_settings :
  title : Jennifer Luk Portfolio
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/JenniferLuk_Headshot.png
    username : Jennifer Luk
    description : Welcome to my portfolio!

  # Icons
  icons :
    email:  lukj4@mcmaster.ca
    linkedin:  https://www.linkedin.com/in/jennifer-lukk/
    github: jenniferlukk
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
